version: '2'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3304:3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
