DROP DATABASE IF EXISTS mygroupwere;
CREATE DATABASE mygroupwere;
USE mygroupwere;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT NOT NULL,
password TEXT NOT NULL,
authority INT NOT NULL,
delete_flag INT NOT NULL,
updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARACTER SET=utf8;
 
DROP TABLE IF EXISTS attendances;
CREATE TABLE attendances (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
work_start_time DATETIME NOT NULL,
work_end_time DATETIME NOT NULL,
break_time TIME NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY fk_user_id(user_id) REFERENCES users(id)
)DEFAULT CHARACTER SET=utf8;

DROP TABLE IF EXISTS emails;
CREATE TABLE emails (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
sender_user_id INT NOT NULL,
receiver_user_id INT NOT NULL,
title TEXT NOT NULL,
message TEXT NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY fk_sender_id(sender_user_id) REFERENCES users(id),
FOREIGN KEY fk_receiver_id(receiver_user_id) REFERENCES users(id)
)DEFAULT CHARACTER SET=utf8;

DROP TABLE IF EXISTS plans;
CREATE TABLE plans (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
content TEXT NOT NULL,
start_time DATETIME NOT NULL,
end_time DATETIME NOT NULL,
remarks TEXT NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY fk_user_id(user_id) REFERENCES users(id)
)DEFAULT CHARACTER SET=utf8;

DROP TABLE IF EXISTS facilities;
CREATE TABLE facilities (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT NOT NULL,
opening_time DATETIME NOT NULL,
closing_time DATETIME NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)DEFAULT CHARACTER SET=utf8;

DROP TABLE IF EXISTS facility_usages;
CREATE TABLE facility_usages (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
facility_id INT NOT NULL,
plan_id INT NOT NULL,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY fk_user_id(user_id) REFERENCES users(id),
FOREIGN KEY fk_facility_id(facility_id) REFERENCES facilities(id),
FOREIGN KEY fk_plan_id(plan_id) REFERENCES plans(id)
)DEFAULT CHARACTER SET=utf8;